### ISSUE TITLE
LIO-SAM not working with bag files captured in gazebo

### ISSUE THREAD

**Issue by esaumar** [engcang/SLAM-application#1]
Hi @engcang! Nice integration, your videos look pretty good. I have been trying to replay what you did with LIO-SAM repo but using another robot. I am using a differential drive robot model (https://github.com/sanuann/DifferentialDriveRobot) where I attached a Velodyne VLP-16 (https://github.com/lmark1/velodyne_simulator) and a IMU (libgazebo_ros_imu.so). 

I can't get a good reconstruction. Have you seen this behavior? I have found that it could be related to the extrinsic parameters in params.yaml but I believe I'm setting the values correctly. 

![lio-sam-velodyne](https://user-images.githubusercontent.com/80426546/120232777-de087800-c219-11eb-9d0a-84dd8eef12a9.png)

I attached the Velodyne into the robot **chassis** using the file **myrobot.xacro** from https://github.com/sanuann/DifferentialDriveRobot

```
<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <VLP-16 parent="chassis" name="velodyne" topic="/velodyne_points" hz="10" samples="440">
    <origin xyz="0 0 0.0" rpy="0 0 0" />
  </VLP-16>
```

![lio-sam-velodyne-3](https://user-images.githubusercontent.com/80426546/120232811-f37da200-c219-11eb-90f5-34c5ac5237fa.png)

I attached the IMU into the **velodyne** body frame and defined an update rate of 500Hz in the file **myrobot.xacro** from https://github.com/sanuann/DifferentialDriveRobot
```
<gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>velodyne</bodyName>
      <topicName>imu</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>500.0</updateRate>
    </plugin>
  </gazebo>
```

Thus, all sensors are in the same body frame, **velodyne**. That is why I used this Extrinsics

```
# Extrinsics (lidar -> IMU)
  extrinsicTrans:  [0.000, 0.000, 0.0]
  extrinsicRot: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]
  extrinsicRPY: [1,  0, 0,
                 0, 1, 0,
                 0, 0, 1]
```
but can't get a good reconstruction. I also tested moving the VLP-16 0.4m above the chassis and modified the Extrinsics to **[0.000, 0.000, -0.438]** (gotten from `rosrun tf tf_echo velodyne chassis`) but I have the same behavior. 
![lio-sam-velodyne-4](https://user-images.githubusercontent.com/80426546/120233434-689da700-c21b-11eb-8d91-57a2fbc2e8b0.png)

Any suggestion will be appreciated. Thanks!

**Comment by esaumar** [comment]
Btw, I tried to use your script `lidar_repair.py` for the trouble shooting with `CPU ray` in the Velodyne Gazebo plugin. I guess the output is the topic with name `velody` but I don't get any point cloud, not even the red ones I showed in the first comment.

**Comment by engcang** [comment]
@esaumar Hi. first thank you for your interest in my repo.
Looking into your questions, I doubt that could because of IMU sensor.
I used `libgazebo_ros_imu_sensor` rather than `libgazebo_ros_imu` and the detailed difference can be found at: http://gazebosim.org/tutorials?tut=ros_gzplugins
According to the original author of LIO-SAM (https://github.com/TixiaoShan/LIO-SAM#prepare-imu-data), you can check that the IMU must include 9-axis values, and I guess it also has to include gravity factor.

Otherwise, exptrinsic parameters seem ok.

**Comment by esaumar** [comment]
Hi again @engcang ! Thanks for your quick response. Finally I got consistent reconstructions with LIO-SAM! You were right, it seemed that it was an issue with the IMU. The gravity should be included in the inertial measurements. I changed the plugin from `libgazebo_ros_imu` to `libgazebo_ros_imu_sensor` as suggested and now it works correctly.

![image (25)](https://user-images.githubusercontent.com/80426546/120560147-dab2ef00-c3c7-11eb-9bad-3e3d262e579f.png)
![image (26)](https://user-images.githubusercontent.com/80426546/120560150-dc7cb280-c3c7-11eb-8672-90a32a7661fb.png)

By using libgazebo_ros_imu_sensor now I can see the gravity on the Z-axis acceleration.
**Bad IMU**

```
orientation: 
  x: 2.27188461314e-06
  y: -4.9678469459e-07
  z: 0.99810920732
  w: -0.0614655208814
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.000769452875622
  y: 0.00324902769181
  z: 4.03222099903e-05
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.227426137416
  y: 0.0242159376913
  z: 4.67897961339
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

**Good IMU**

```
orientation: 
  x: 1.55563938577e-14
  y: -6.53325214776e-15
  z: -2.5826076197e-15
  w: 1.0
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -6.18309291924e-13
  y: 2.5967517029e-13
  z: 6.44077756609e-21
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 1.2805174418e-13
  y: 3.04905318523e-13
  z: 9.8
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

```
Thanks for your support!
